wandb:
  project: "irfl-v2-3m"

# Use the same model configuration for each modality, except for the positional encoding parameters and input channels which are modality-specific
perceiver: 
  type: "disen" # "standard" or "disen"
  depth: 4 # Number of layers in the Perceiver model
  max_freq: null
  num_freq_bands: null
  input_channels: [768, 512, 512] # Input channels for each modality
  input_axis: 1
  num_latents: 4 # Number of latent vectors, i.e. the number of disentangled factors to extract from each modality
  cross_heads: 2
  pos_encoding: true
  latent_dim: 256 # The dimension of each latent vector
  weight_tie_layers: false
  
repercent:
  M: 3 # Number of modalities
  disen_mapping:
    M_1:
      U_12: 0
      S_12: 1
      U_13: 2
      S_13: 3
    M_2:
      U_21: 0
      S_21: 1
      U_23: 2
      S_23: 3
    M_3:
      U_31: 0
      S_31: 1
      U_32: 2
      S_32: 3
  vmfkappa: 1000