wandb:
  project: "irfl-v2-2m"


# The paths to the checkpoints are wrt the root of the repository
repercent:
  checkpoints:
    - "./checkpoints/irfl/2026-03-09_13-33-04_IRFL_repercent_seeds_5_seed_0/seed0/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-09_13-33-04_IRFL_repercent_seeds_5_seed_1/seed1/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-09_13-33-04_IRFL_repercent_seeds_5_seed_2/seed2/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-09_13-33-04_IRFL_repercent_seeds_5_seed_3/seed3/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-09_13-33-04_IRFL_repercent_seeds_5_seed_4/seed4/final_checkpoint.pt"


    
gmlp:
  checkpoints:
    - "./checkpoints/irfl/2026-03-09_12-53-51_IRFL_gmlp_seeds_5_seed_0/seed0/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-09_12-53-51_IRFL_gmlp_seeds_5_seed_1/seed1/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-09_12-53-51_IRFL_gmlp_seeds_5_seed_2/seed2/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-09_12-53-51_IRFL_gmlp_seeds_5_seed_3/seed3/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-09_12-53-51_IRFL_gmlp_seeds_5_seed_4/seed4/final_checkpoint.pt"

gru:
  checkpoints:
    - "./checkpoints/irfl/2026-03-18_12-18-22_IRFL_gru_seeds_5_seed_0/seed0/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-18_12-18-22_IRFL_gru_seeds_5_seed_1/seed1/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-18_12-18-22_IRFL_gru_seeds_5_seed_2/seed2/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-18_12-18-22_IRFL_gru_seeds_5_seed_3/seed3/final_checkpoint.pt"
    - "./checkpoints/irfl/2026-03-18_12-18-22_IRFL_gru_seeds_5_seed_4/seed4/final_checkpoint.pt"

hyperparameters:
  max_distractors: 3 # Max number of distractors
  n_distractors: [1, 2, 3] # Number of distractors to use in the evaluation - upper bounded by 3 given the dataset
  n_seeds: 5 # Number of seeds used in the experiments