_wandb:
    value:
        cli_version: 0.23.0
        e:
            nfzsp3c3elxhentmfpjbsdza7j8dd9yk:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "7679362727936"
                        used: "5738861645824"
                email: vasiliki.rizou@epfl.ch
                executable: /usr/bin/python
                git:
                    remote: https://github.com/Vascorn/lts4-FaP.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-891fc29b-8bf6-977d-cfe0-021c9eb1418c
                host: runai-job-1765456012-0-0
                memory:
                    total: "1081885040640"
                os: Linux-6.8.0-59-generic-x86_64-with-glibc2.35
                program: /mnt/lts4-dislearn/scratch/home/rizou/lts4-FaP/training/./main.py
                python: CPython 3.10.12
                root: /mnt/lts4-dislearn/scratch/home/rizou/lts4-FaP/training
                startedAt: "2025-12-11T16:47:28.640832Z"
                writerId: nfzsp3c3elxhentmfpjbsdza7j8dd9yk
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "4": 3.10.12
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
