wandb:
  project: "honeybee-4m"


disen_loss:
  alpha: 2.0
  lmd: 5.0
  lmd_start_value: 2.0
  lmd_end_value: 3.0
  lmd_n_iterations: 600
  lmd_start_iteration: 200
  ortho_norm: true


optimizer:
  name: "adam"
  lr: 0.00005
  weight_decay: 0.0005



training:
  test_size: 0.2
  n_epochs: 50
  batch_size: 256
  log_interval: 10
  augmentation: "random" # This includes all three augmentation types: noise, swap, random_drop