wandb:
  project: "synthetic-data-2-modalities"



disen_loss:
  alpha: 0.5
  lmd: 0.005
  lmd_start_value: 0.001
  lmd_end_value: 0
  lmd_n_iterations: 10000
  lmd_start_iteration: 5000
  ortho_norm: true


optimizer:
  name: "adam"
  lr: 0.001
  weight_decay: 0.00001



training:
  test_size: 0.2
  n_epochs: 50
  batch_size: 1024
  log_interval: 10
  augmentation: "random" # This includes all three augmentation types: noise, swap, random_drop
  