wandb:
  project: "synthetic-moe-3M"



disen_loss:
  alpha: 20.0
  lmd: 0.001
  lmd_start_value: 0.1
  lmd_end_value: 1.0
  lmd_n_iterations: 8000
  lmd_start_iteration: 800
  ortho_norm: true

optimizer:
  name: "adam"
  lr: 0.0008
  weight_decay: 0.0001



training:
  val_size: 0.1
  test_size: 0.2
  n_epochs: 50
  batch_size: 1024
  log_interval: 10
  augmentation: "random" # This includes to augmentation types: noise, random_drop
  