wandb:
  project: "irfl-2m-final"


disen_loss:
  alpha: 6.0
  lmd: 4.0
  lmd_start_value: 1.0
  lmd_end_value: 0
  lmd_n_iterations: 250
  lmd_start_iteration: 50
  beta: 2.0
  ortho_norm: true


optimizer:
  name: "adam"
  lr: 0.0001
  weight_decay: 0.0001



training:
  test_size: 0.2
  n_epochs: 30
  batch_size: 256
  log_interval: 10
  augmentation: "random" # This includes all three augmentation types: noise, swap, random_drop