method: 'random'
metric:
  name: 'best_val_loss'
  goal: 'minimize'

parameters:
  lr:
    distribution: 'log_uniform_values'
    min: 0.00001
    max: 0.0002
  batch_size: 
    value: 512
  num_epochs: 
    value: 50
  # cross_heads: 
  #   values: [1, 2]
  # latent_heads: 
  #   values: [1, 2]
  depth: 
    values: [1, 2]
  weight_tie_layers: 
    value: true